### PR TITLE
added conference links

### PR DESCRIPTION
**Pull request by handwerkerd**
I thought it would be nice to add the links to our OHBM conference repos to this page.

### CODE REVIEW

**Comment by handwerkerd** [comment]
@tsalo I was going to ask you to review/merge if you're ok with this, but I'm realizing I don't have the ability to assign reviewers for this repo. My guess is that only the two owners can do that. Maybe give all the devs that authority?

**Comment by tsalo** [comment]
I gave the dev team maintainer permissions to this repo. I'd love to give the team write permissions to all newly-created repos by default, but I don't know if that's possible. The best I could figure out how to do would be to give all organization members write permissions, but I don't think we want to do that if we plan on expanding the organization at any point.

**Review by tsalo — COMMENTED** [review]
Are the scientific conferences meant to apply to the organization as a whole, or to tedana specifically? If the latter, then maybe we could nest the scientific conferences under the tedana section.

**Comment by eurunuela** [comment]
> Are the scientific conferences meant to apply to the organization as a whole, or to tedana specifically? If the latter, then maybe we could nest the scientific conferences under the tedana section.

I guess it depends on whether the non-tedana projects submit to conferences. I'm expecting tedana and rica to be the only ones after OHBM, so it wouldn't be a big deal at all to have an organization-wide list.

**Comment by handwerkerd** [comment]
For each of the conference I've compiled all multi-echo abstracts whether or not they use tedana, so they're definitely about more than tedana. I figure any conference that someone decides to organize the multi-echo presentations can be added. I'd lean towards keeping it distinct from tedana.

**Review by tsalo — APPROVED** [review]
That's fair. I'd like to distinguish software and other elements to the organization, though, so perhaps we could add a new heading 2 called "Software tools" or something, and bump all of the software-specific sections down to heading 3s.

I'm happy to address that in a future PR, though, so I'm approving.

**Pull request merged**
